name: dbt_run_on_push
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]

env:
 DBT_PROFILES_DIR: ./

 DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
 DBT_SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USER }}
 DBT_SNOWFLAKE_PW: ${{ secrets.SNOWFLAKE_PASSWORD }}
 DBT_SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}

jobs:
 dbt_run_on_push:
    name: dbt_run_on_push
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
    
      - name: Install dependencies
        run: |
          pip install dbt-snowflake==1.6.0
    
        # dbt related commands here - run use --target prod/dev to run for specific environments
      - name: Run dbt models
        run: dbt run
